$(function(){
    $("#main_youtv").click(function(){
        $("#modal_wrap").fadeIn()
    });
    $("#close").click(function(){
        $("#modal_wrap").fadeOut()
    });
    $("#modal_wrap").click(function(){
        $("#modal_wrap").fadeOut()
    });
})